[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Sepolia Testnet Configuration
[rpc_endpoints]
# sepolia = "https://eth-sepolia.g.alchemy.com/v2/4EkFRqr0TW4yTDAmYR9AO"
# lisk-testnet = "https://rpc.sepolia-api.lisk.com"

# forge verify-contract   --rpc-url https://rpc.sepolia-api.lisk.com   --verifier blockscout   --verifier-url 'https://sepolia-blockscout.lisk.com/api/'    0x22Acda4103f0EFf4d0202E412ecf970bc6BE53a3 src/facets/DiamondLoupeFacet.sol:DiamondLoupeFacet 



[etherscan]
lisk-testnet = { key = "123", chain=4202, url="https://sepolia-blockscout.lisk.com/api/" }
[profile.EtherscanConfig]
etherscan.chain="4202"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
